### ISSUE TITLE
Eager initializer ignores sidekiq config

### ISSUE THREAD

**Issue by iwarshak** [spacebabies/sidekiq_snitch#2]
It seems that having the initializer in the engine enqueue a `Sidekiq::Snitch.perform_async` job forces sidekiq to initialize before it's customization initializer is read.

For instance, my sidekiq initializer has a namespace setup, 

```
  Sidekiq.configure_server do |config|
    config.redis = { :url => $redis_connection_url, :namespace => 'fooqueue' }
  end
```

This block never gets executed by sidekiq because the call to `Sidekiq::Snitch.perform_async` forces sidekiq to initialize with the defaults, which does not include the namespace. 

Proposed solution: Making user make initial call to `Sidekiq::Snitch.perform_async` at the end of their sidekiq initializer.

Using sidekiq 2.17.8

**Comment by tilsammans** [comment]
I'm not against the solution but it would be better if the gem continues to work out of the box.

If my gem could delay scheduling the job after some kind of Sidekiq "after config" event that would be preferable. I'll try the Sidekiq source to see if there is such a thing.

**Comment by tilsammans** [comment]
I‘ve stopped maintaining this gem, since I think OkComputer is a superior solution to monitoring your Sidekiq queue. You would add one for each queue, and then check the /okcomputer endpoint for everything.
